import {Dimensions, StyleSheet} from 'react-native';
import colors from '../../contants/colors';

const {width} = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    flex: 1,
    overflow: 'hidden',
    justifyContent: 'space-between',
  },
  timerContainer: {
    backgroundColor: colors.white,
    borderRadius: 35,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    flexDirection: 'row',
    paddingVertical: 5,
  },
  timer: {
    color: colors.D3A4E,
    fontSize: 15,
    fontWeight: '700',
    marginRight: 10,
  },
  heading: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.white,
  },
  cardContainer: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.34,
    shadowRadius: 6.27,
    elevation: 10,
    borderRadius: 8,
    backgroundColor: colors.white,
    marginHorizontal: 16,
    marginBottom: 20,
  },
  shadow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 21,
    borderRadius: 35,
  },
  cardHeader: {},
  cardHeaderLeft: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  topicContainer: {
    paddingLeft: 10,
    borderTopLeftRadius: 8,
    borderBottomRightRadius: 80,
    backgroundColor: colors.white,
  },
  cardHeaderRight: {
    paddingRight: 10,
  },
  topic: {
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  paperShadow: {
    // shadowColor: '#000',
    // shadowOffset: {
    //     width: 0,
    //     height: 3,
    // },
    // shadowOpacity: 0.6,
    // shadowRadius: 3,
    // elevation: 24,
    // backgroundColor: colors.white,
    width: 100,
    borderWidth: 1,
    borderColor: colors.red,
    borderRadius: 35,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 2,
    alignSelf: 'center',
  },
  paperText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.white,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    backgroundColor: colors.F3F3F3,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    paddingVertical: 5,
    marginTop: 15,
  },
  footerLabel: {
    fontSize: 8,
    fontWeight: '600',
    color: colors.grey,
  },
  footerValue: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.black,
    marginLeft: 2,
  },
  footerOption: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  winning: {
    width: 10,
    height: 15,
    marginRight: 5,
  },
  tab: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginLeft: 15,
    borderWidth: 1,
    borderRadius: 35,
    marginVertical: 10,
  },
  tabText: {
    fontWeight: '600',
  },
  selected: {
    backgroundColor: colors.I86B91,
    borderColor: colors.I86B91,
  },
  filerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  otherFilter: {
    flexDirection: 'row',
    backgroundColor: colors.I86B91,
    alignItems: 'center',
    borderRadius: 35,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  filterText: {
    color: colors.white,
    fontWeight: '600',
    marginRight: 5,
    fontSize: 12,
  },
  modalbox: {
    height: null,
    width: '100%',
    backgroundColor: colors.white,
    padding: 16,
    borderTopStartRadius: 16,
    borderTopEndRadius: 16,
  },
  close: {
    height: 12,
    width: 12,
  },
  modal_heading: {
    borderBottomWidth: 0.5,
    lineHeight: 35,
    flex: 1,
    textAlign: 'center',
    color: colors.black,
  },
  refer_code: {
    fontSize: 20,
    fontWeight: '800',
  },
  btn: {
    width: '100%',
    alignSelf: 'center',
    marginVertical: 20,
  },
  option: {
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  check: {
    width: 18,
    height: 18,
  },
  editCta: {
    color: colors.I86B91,
    fontWeight: '700',
    fontSize: 20,
  },
  iconContainer: {
    borderWidth: 0.5,
    borderRadius: 100,
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  feature: {
    flexDirection: 'row',
    width: Dimensions.get('screen').width / 2,
  },
  featureLabel: {
    color: colors.grey,
    fontWeight: '500',
    fontSize: 12,
  },
  featureValue: {
    fontWeight: '800',
    fontSize: 12,
  },
  button: {
    width: width - 40,
    borderRadius: 100,
    alignSelf: 'center',
  },
  text: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
    paddingVertical: 10,
    textAlign: 'center',
  },
  timeLimit: {
    color: colors.red,
    fontWeight: '800',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 15,
    marginBottom: 20,
  },
  rulesTabs: {
    flexDirection: 'row',
  },
  rulesTab: {
    width: Dimensions.get('screen').width / 2,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 10,
  },
  selectedRuleTab: {
    borderBottomWidth: 2,
    borderBottomColor: colors.A0374A8,
  },
  rulesTabText: {
    color: colors.grey,
    fontWeight: '800',
  },
  selectedRuleTabText: {
    color: colors.A0374A8,
  },
  tabsData: {
    flexDirection: 'row',
    paddingHorizontal: 50,
    marginTop: 20,
  },
  tabData: {
    width: Dimensions.get('screen').width / 2,
    fontSize: 15,
    fontWeight: '800',
  },
  rulesTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 10,
  },
  rulesDes: {
    marginVertical: 2,
  },
});
