export default {
  bell: require('../assets/bell.png'),
  bottom_home: require('../assets/BottomTab/Home.png'),
  bottom_test: require('../assets/BottomTab/Book.png'),
  bottom_search: require('../assets/BottomTab/Search.png'),
  bottom_topper: require('../assets/BottomTab/Topper.png'),
  exams: require('../assets/exams.png'),
  topics: require('../assets/topics.png'),
  subjects: require('../assets/subjects.png'),
  splash_icon: require('../assets/splash_icon.png'),
  google_icon: require('../assets/google_icon.png'),
  exam_chip: require('../assets/exam_chip.png'),
  back: require('../assets/back.png'),
  cross: require('../assets/cross.png'),
  menu: require('../assets/Menu.png'),
  profile: require('../assets/profile.png'),
  wallet: require('../assets/Wallet.png'),
  notification: require('../assets/notification.png'),
};
